---

# Main collection of env. vars to set for all tasks and scripts.
env:
    IMAGE_SUFFIX: "c6323493627232256"
    FEDORA_CONTAINER_FQIN: "quay.io/libpod/fedora_podman:${IMAGE_SUFFIX}"


# Default timeout for each task
timeout_in: 10m


failing_test_task:
    only_if: $CIRRUS_CRON != ''
    container:
        image: ${FEDORA_CONTAINER_FQIN}
        cpu: 2
        memory: 2
    script: /bin/false


passing_test_task:
    container:
        image: ${FEDORA_CONTAINER_FQIN}
        cpu: 2
        memory: 2
    script: /bin/true
